version: '3'

services:
  db:
    build:
      context: postgres
      dockerfile: ./Dockerfile
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_INITDB_ARGS=--encoding=UTF-8
    tty: true
    restart: always
    user: root
    volumes:
      - ./postgres/init:/docker-entrypoint-initdb.d
  api:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 8080:8080
    tty: true
    depends_on:
      - db